version: '3.2'
services:
  keycloak:
    env_file: .env
    image: hellobrett/keycloak-examples
    ports:
     - "8080:8080"
  wildfly:
    env_file: .env
    image: jboss/keycloak-adapter-wildfly:3.4.3.Final
    ports:
     - "9990:9990"
     - "8180:8080"
    environment:
      - KEYCLOAK_VERSION=3.4.3.Final
#    TO DO: Why does this command not work?  It works from inside the container...
#    command: "/opt/jboss/wildfly/bin/add-user.sh -u ${KEYCLOAK_USER} -p ${KEYCLOAK_PASSWORD}"
    entrypoint: "/opt/jboss/wildfly/bin/standalone.sh -bmanagement 0.0.0.0"
