version: '3.2'
services:
  keycloak:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    ports:
     - "8080:8080"
  wildfly:
    image: jboss/keycloak-adapter-wildfly:3.4.3.Final
    ports:
     - "9990:9990"
    environment:
      - KEYCLOAK_VERSION=3.4.3.Final
    entrypoint: "/opt/jboss/wildfly/bin/standalone.sh -bmanagement 0.0.0.0"
